#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  IkaLog
#  ======
#  Copyright (C) 2015 Takeshi HASEGAWA
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

#  IkaLog Constants

stages = {
    'anchovy': {'ja': 'アンチョビットゲームズ', 'en': 'Ancho-V Games'},
    'arowana':  {'ja': 'アロワナモール',      'en': 'Arowana Mall'},
    'bbass':    {'ja': 'Bバスパーク',         'en': 'Blackbelly Skatepark'},
    'dekaline': {'ja': 'デカライン高架下',    'en': 'Urchin Underpass'},
    'hakofugu': {'ja': 'ハコフグ倉庫',        'en': 'Walleye Warehouse', },
    'hirame':   {'ja': 'ヒラメが丘団地',      'en': 'Flounder Heights', },
    'hokke':    {'ja': 'ホッケふ頭',          'en': 'Port Mackerel'},
    'kinmedai': {'ja': 'キンメダイ美術館',    'en': 'Museum d\'Alfonsino'},
    'mahimahi': {'ja': 'マヒマヒリゾート&スパ', 'en': 'Mahi-Mahi Resort', },
    'masaba':   {'ja': 'マサバ海峡大橋',      'en': 'Hammerhead Bridge', },
    'mongara':  {'ja': 'モンガラキャンプ場',  'en': 'Camp Triggerfish', },
    'mozuku':   {'ja':  'モズク農園',         'en': 'Kelp Dome', },
    'negitoro': {'ja': 'ネギトロ炭鉱',        'en': 'Bluefin Depot', },
    'shionome': {'ja': 'シオノメ油田',        'en': 'Saltspray Rig', },
    'shottsuru': {'ja': 'ショッツル鉱山',     'en': 'Piranha Pit'},
    'tachiuo':  {'ja':  'タチウオパーキング', 'en':  'Moray Towers', },
}

rules = {
    'nawabari': {'ja': 'ナワバリバトル', 'en': 'Turf War', },
    'area': {'ja': 'ガチエリア', 'en': 'Splat Zones', },
    'yagura': {'ja': 'ガチヤグラ', 'en': 'Tower Control', },
    'hoko': {'ja': 'ガチホコバトル', 'en': 'Rainmaker', },
}

weapons = {
    '52gal': {'ja': '.52ガロン', 'en': '.52 Gal'},
    '52gal_deco': {'ja': '.52ガロンデコ', 'en': '.52 Gal Deco'},
    '96gal': {'ja': '.96ガロン', 'en': '.96 Gal'},
    '96gal_deco': {'ja': '.96ガロンデコ', 'en': '.96 Gal Deco'},
    'bold': {'ja': 'ボールドマーカー', 'en': 'Sploosh-o-matic'},
    'bold_7': {'ja': 'ボールドマーカー7', 'en': 'Sploosh-o-matic 7'},
    'bold_neo': {'ja': 'ボールドマーカーネオ', 'en': 'Neo Sploosh-o-matic'},
    'dualsweeper': {'ja': 'デュアルスイーパー', 'en': 'Dual Squelcher'},
    'dualsweeper_custom': {'ja': 'デュアルスイーパーカスタム', 'en': 'Custom Dual Squelcher'},
    'h3reelgun': {'ja': 'H3リールガン', 'en': 'H-3 Nozzlenose'},
    'h3reelgun_cherry': {'ja': 'H3リールガンチェリー', 'en': 'Cherry H-3 Nozzlenose'},
    'h3reelgun_d': {'ja': 'H3リールガンD', 'en': 'H-3 Nozzlenose D'},
    'heroshooter_replica': {'ja': 'ヒーローシューターレプリカ', 'en': 'Hero Shot Replica'},
    'hotblaster': {'ja': 'ホットブラスター', 'en': 'Blaster'},
    'hotblaster_custom': {'ja': 'ホットブラスターカスタム', 'en': 'Custom Blaster'},
    'jetsweeper': {'ja': 'ジェットスイーパー', 'en': 'Jet Squelcher'},
    'jetsweeper_custom': {'ja': 'ジェットスイーパーカスタム', 'en': 'Custom Jet Squelcher'},
    'l3reelgun': {'ja': 'L3リールガン', 'en': 'L-3 Nozzlenose'},
    'l3reelgun_d': {'ja': 'L3リールガンD', 'en': 'L-3 Nozzlenose D'},
    'longblaster': {'ja': 'ロングブラスター', 'en': 'Range Blaster'},
    'longblaster_custom': {'ja': 'ロングブラスターカスタム', 'en': 'Custom Range laster'},
    'longblaster_necro': {'ja': 'ロングブラスターネクロ', 'en': 'Grim Range laster'},
    'momiji': {'ja': 'もみじシューター', 'en': 'Custom Splattershot Jr.'},
    'nova': {'ja': 'ノヴァブラスター', 'en': 'Luna Blaster'},
    'nova_neo': {'ja': 'ノヴァブラスターネオ', 'en': 'Luna Blaster Neo'},
    'nzap83': {'ja': 'N-ZAP83', 'en': 'N-ZAP \'83'},
    'nzap85': {'ja': 'N-ZAP85', 'en': 'N-ZAP \'85'},
    'nzap89': {'ja': 'N-ZAP89', 'en': 'N-Zap \'89'},
    'octoshooter_replica': {'ja': 'オクタシューターレプリカ', 'en': 'Octoshot Replica'},
    'prime': {'ja': 'プライムシューター', 'en': 'Splattershot Pro'},
    'prime_berry': {'ja': 'プライムシューターベリー', 'en': 'Berry Splattershot Pro'},
    'prime_collabo': {'ja': 'プライムシューターコラボ', 'en': 'Forge Splattershot Pro'},
    'promodeler_mg': {'ja': 'プロモデラーMG', 'en': 'Aerospray MG'},
    'promodeler_pg': {'ja': 'プロモデラーPG', 'en': 'Aerospray PG'},
    'promodeler_rg': {'ja': 'プロモデラーRG', 'en': 'Aerospray RG'},
    'rapid': {'ja': 'ラピッドブラスター', 'en': 'Rapid Blaster'},
    'rapid_deco': {'ja': 'ラピッドブラスターデコ', 'en': 'Rapid Blaster Deco'},
    'rapid_elite': {'ja': 'Rブラスターエリート', 'en': 'Rapid Blaster Pro'},
    'rapid_elite_deco': {'ja': 'Rブラスターエリートデコ', 'en': 'Rapid Blaster Pro Deco'},
    'sharp': {'ja': 'シャープマーカー', 'en': 'Splash-o-matic'},
    'sharp_neo': {'ja': 'シャープマーカーネオ', 'en': 'Neo Splash-o-matic'},
    'sshooter': {'ja': 'スプラシューター', 'en': 'Splattershot'},
    'sshooter_collabo': {'ja': 'スプラシューターコラボ', 'en': 'Tentatek Splattershot'},
    'sshooter_wasabi': {'ja': 'スプラシューターワサビ', 'en': 'Wasabi Splattershot'},
    'wakaba': {'ja': 'わかばシューター', 'en': 'Splattershot Jr.'},

    'carbon': {'ja': 'カーボンローラー', 'en': 'Carbon Roller'},
    'carbon_deco': {'ja': 'カーボンローラーデコ', 'en': 'Carbon Roller Deco'},
    'dynamo': {'ja': 'ダイナモローラー', 'en': 'Dynamo Roller'},
    'dynamo_burned': {'ja': 'ダイナモローラーバーンド', 'en': 'Tempered Dynamo Roller'},
    'dynamo_tesla': {'ja': 'ダイナモローラーテスラ', 'en': 'Gold Dynamo Roller'},
    'heroroller_replica': {'ja': 'ヒーローローラーレプリカ', 'en': 'Hero Roller Replica'},
    'hokusai': {'ja': 'ホクサイ', 'en': 'Octobrush'},
    'hokusai_hue': {'ja': 'ホクサイ・ヒュー', 'en': 'Octobrush Nouveau'},
    'pablo': {'ja': 'パブロ', 'en': 'Inkbrush'},
    'pablo_hue': {'ja': 'パブロ・ヒュー', 'en': 'Inkbrush Nouveau'},
    'pablo_permanent': {'ja': 'パーマネント・パブロ', 'en': 'Permanent Inkbrush'},
    'splatroller': {'ja': 'スプラローラー', 'en': 'Splat Roller'},
    'splatroller_collabo': {'ja': 'スプラローラーコラボ', 'en': 'Krak-On Splat Roller'},
    'splatroller_corocoro': {'ja': 'スプラローラーコロコロ', 'en': 'CoroCoro Splat Roller'},

    'bamboo14mk1': {'ja': '14式竹筒銃・甲', 'en': 'Bamboozler 14 MK I'},
    'bamboo14mk2': {'ja': '14式竹筒銃・乙', 'en': 'Bamboozler 14 MK II'},
    'bamboo14mk3': {'ja': '14式竹筒銃・丙', 'en': 'Bamboozler 14 Mk III'},
    'herocharger_replica': {'ja': 'ヒーローチャージャーレプリカ', 'en': 'Hero Charger Replica'},
    'liter3k': {'ja': 'リッター3K', 'en': 'E-liter 3K'},
    'liter3k_custom': {'ja': 'リッター3Kカスタム', 'en': 'Custom E-liter 3K'},
    'liter3k_scope': {'ja': '3Kスコープ', 'en': 'E-liter 3K Scope'},
    'liter3k_scope_custom': {'ja': '3Kスコープカスタム', 'en': 'Custom E-liter 3K Scope'},
    'splatcharger': {'ja': 'スプラチャージャー', 'en': 'Splat Charger'},
    'splatcharger_bento': {'ja': 'スプラチャージャーベントー', 'en': 'Bento Splat Charger'},
    'splatcharger_wakame': {'ja': 'スプラチャージャーワカメ', 'en': 'Kelp Splat Charger'},
    'splatscope': {'ja': 'スプラスコープ', 'en': 'Splatterscope'},
    'splatscope_bento': {'ja': 'スプラスコープベントー', 'en': 'Bento Splatterscope'},
    'splatscope_wakame': {'ja': 'スプラスコープワカメ', 'en': 'Kelp Splatterscope'},
    'squiclean_a': {'ja': 'スクイックリンα', 'en': 'Classic Squiffer'},
    'squiclean_b': {'ja': 'スクイックリンβ', 'en': 'New Squiffer'},
    'squiclean_g': {'ja': 'スクイックリンγ', 'en': 'Fresh Squiffer'},

    'bucketslosher': {'ja': 'バケットスロッシャー', 'en': 'Slosher'},
    'bucketslosher_deco': {'ja': 'バケットスロッシャーデコ', 'en': 'Slosher Deco'},
    'bucketslosher_soda': {'ja': 'バケットスロッシャーソーダ', 'en': 'Soda Slosher'},
    'hissen': {'ja': 'ヒッセン', 'en': 'Tri-Slosher'},
    'hissen_hue': {'ja': 'ヒッセン・ヒュー', 'en': 'Tri-Slosher Nouveau'},
    'screwslosher': {'ja': 'スクリュースロッシャー', 'en': 'Sloshing Machine'},
    'screwslosher_neo': {'ja': 'スクリュースロッシャーネオ', 'en': 'Sloshing Machine Neo'},

    'barrelspinner': {'ja': 'バレルスピナー', 'en': 'Heavy Splatling'},
    'barrelspinner_deco': {'ja': 'バレルスピナーデコ', 'en': 'Heavy Splatling Deco'},
    'barrelspinner_remix': {'ja': 'バレルスピナーリミックス', 'en': 'Heavy Splatling Remix'},
    'hydra': {'ja': 'ハイドラント', 'en': 'Hydra Splatling'},
    'hydra_custom': {'ja': 'ハイドラントカスタム', 'en': 'Custom Hydra Splatling'},
    'splatspinner': {'ja': 'スプラスピナー', 'en': 'Mini Splatling'},
    'splatspinner_collabo': {'ja': 'スプラスピナーコラボ', 'en': 'Zink Mini Splatling'},
    'splatspinner_repair': {'ja': 'スプラスピナーリペア', 'en': 'Refurbished Mini Splatling'},
}

sub_weapons = {
    'chasebomb': {'ja': 'チェイスボム', 'en':  'Seeker', },
    'jumpbeacon': {'ja': 'ジャンプビーコン', 'en':  'Squid Beakon', },
    'kyubanbomb': {'ja': 'キューバンボム', 'en':  'Suction Bomb', },
    'pointsensor': {'ja': 'ポイントセンサー', 'en':  'Point Sensor', },
    'poison': {'ja': 'ポイズンボール', 'en':  'Disruptor', },
    'quickbomb': {'ja': 'クイックボム', 'en':  'Burst Bomb', },
    'splashbomb': {'ja': 'スプラッシュボム', 'en':  'Splat Bomb', },
    'splashshield': {'ja': 'スプラッシュシールド', 'en':  'Splash Wall', },
    'sprinkler': {'ja': 'スプリンクラー', 'en':  'Sprinkler', },
    'trap': {'ja': 'トラップ', 'en':  'Ink Mine', },
}

deadly_sub_weapons = [
    'chasebomb', 'kyubanbomb', 'quickbomb', 'splashbomb', 'splashshield',
    'sprinkler', 'trap',
]

special_weapons = {
    'barrier': {'ja': 'バリア', 'en':  'Bubbler', },
    'bombrush': {'ja': 'ボムラッシュ', 'en':  'Bomb Rush', },
    'daioika': {'ja': 'ダイオウイカ', 'en':  'Kraken', },
    'megaphone': {'ja': 'メガホンレーザー', 'en':  'Killer Wail', },
    'supersensor': {'ja': 'スーパーセンサー', 'en':  'Echolocator', },
    'supershot': {'ja': 'スーパーショット', 'en':  'Inkzooka', },
    'tornado': {'ja': 'トルネード', 'en':  'Inkstrike', },
}

deadly_special_weapons = ['daioika', 'megaphone', 'supershot', 'tornado', ]

hurtable_objects = {
    'hoko_shot': {'ja': 'ガチホコショット', 'en': 'Rainmaker Shot', },
    'hoko_barrier': {'ja': 'ガチホコバリア', 'en': 'Rainmaker Shield', },
    'hoko_inksplode': {'ja': 'ガチホコ爆発', 'en': 'Rainmaker Inksplode', },

    'propeller': {'ja': 'プロペラから飛び散ったインク', 'en': 'Ink from a propeller'},
}

oob_reasons = {
    'oob': {'ja': '場外', 'en': 'Out of Bounds', },
    'fall': {'ja': '転落', 'en': 'Fall', },
    'drown': {'ja': '水死', 'en': 'Drowning', },
}

udemae_strings = [
    's+', 's', 'a+', 'a', 'a-', 'b+', 'b', 'b-', 'c+', 'c', 'c-'
]

fes_rank_titles = [
    'fanboy', 'fiend', 'defender', 'champion', 'king'
]


gear_abilities = {
    'bomb_range_up': {'ja': 'ボム飛距離アップ', 'en': 'Bomb Range Up'},
    'bomb_sniffer': {'ja': 'ボムサーチ', 'en': 'Bomb Sniffer'},
    'cold_blooded': {'ja': 'マーキングガード', 'en': 'Cold Blooded'},
    'comeback': {'ja': 'カムバック', 'en': 'Comeback'},
    'damage_up': {'ja': '攻撃力アップ', 'en': 'Damage Up'},
    'defense_up': {'ja': '防御力アップ', 'en': 'Defense Up'},
    'empty': {'ja': '空', 'en': 'Empty'},
    'haunt': {'ja': 'うらみ', 'en': 'Haunt'},
    'ink_recovery_up': {'ja': 'インク回復力アップ', 'en': 'Ink Recovery Up'},
    'ink_resistance_up': {'ja': '安全シューズ', 'en': 'Ink Resistance'},
    'ink_saver_main': {'ja': 'インク効率アップ（メイン）', 'en': 'Ink Saver (Main)'},
    'ink_saver_sub': {'ja': 'インク効率アップ（サブ）', 'en': 'Ink Saver (Sub)'},
    'last_ditch_effort': {'ja': 'ラストスパート', 'en': 'Last-Ditch Effort'},
    'locked': {'ja': '未開放', 'en': 'Locked'},
    'ninja_squid': {'ja': 'イカニンジャ', 'en': 'Ninja Squid'},
    'opening_gambit': {'ja': 'スタートダッシュ', 'en': 'Opening Gambit'},
    'quick_respawn': {'ja': '復活時間短縮', 'en': 'Quick Respawn'},
    'quick_super_jump': {'ja': 'スーパージャンプ時間短縮', 'en': 'Quick Super Jump'},
    'recon': {'ja': 'スタートレーダー', 'en': 'Recon'},
    'run_speed_up': {'ja': 'ヒト移動速度アップ', 'en': 'Run Speed Up'},
    'special_charge_up': {'ja':  'スペシャル増加量アップ', 'en': 'Special Charge Up'},
    'special_duration_up': {'ja':  'スペシャル時間延長', 'en': 'Special Duration Up'},
    'special_saver': {'ja':  'スペシャル減少量ダウン', 'en': 'Special Saver'},
    'stealth_jump': {'ja':  'ステルスジャンプ', 'en': 'Stealth Jump'},
    'swim_speed_up': {'ja':  'イカダッシュ速度アップ', 'en': 'Swim Speed Up'},
    'tenacity': {'ja':  '逆境', 'en': 'Tenacity'}
}

gear_brands = {
    'amiibo':     {'ja': 'amiibo', 'en': 'amiibo', },
    'cuttlegear': {'ja': 'アタリメイド', 'en': 'Cuttlegear', },
    'famitsu':    {'ja': 'ファミ通', 'en': 'Famitsu', },
    'firefin':    {'ja': 'ホッコリー', 'en': 'Firefin', },
    'forge':      {'ja': 'Forge', 'en': 'Forge', },
    'inkline':    {'ja': 'Inkline', 'en': 'Inkline', },
    'kog':        {'ja': 'KOG', 'en': 'KOG', },
    'krakon':     {'ja': 'クラーゲス', 'en': 'Krak-On', },
    'rockenberg': {'ja': 'ロッケンベルグ', 'en': 'Rockenberg', },
    'skalop':     {'ja': 'ホタックス', 'en': 'Skalop', },
    'splashmob':  {'ja': 'ジモン', 'en': 'Splash Mob', },
    'squidforce': {'ja': 'バトロイカ', 'en': 'Squidforce', },
    'squidgirl':  {'ja': '侵略！イカ娘', 'en': 'SQUID GIRL', },
    'takoroka':   {'ja': 'ヤコ', 'en': 'Takoroka', },
    'tentatek':   {'ja': 'アロメ', 'en': 'Tentatek', },
    'zekko':      {'ja': 'エゾッコ', 'en': 'Zekko', },
    'zink':       {'ja': 'アイロニック', 'en': 'Zink', },
}


gear_headgear = {
    '18k_aviators': { 'en': '18K Aviators', 'ja': 'タレサン18K' },
    'armor_helmet_replica': { 'en': 'Armor Helmet Replica', 'ja': 'アーマーメット レプリカ' },
    'b_ball_headband': { 'en': 'B-ball Headband', 'ja': 'バスケバンド' },
    'backwards_cap': { 'en': 'Backwards Cap', 'ja': 'バックワードキャップ' },
    'bamboo_hat': { 'en': 'Bamboo Hat', 'ja': 'スゲ' },
    'bike_helmet': { 'en': 'Bike Helmet', 'ja': 'サイクルメット' },
    'black_arrowbands': { 'en': 'Black Arrowbands', 'ja': 'アローバンドブラック' },
    'blowfish_bell_hat': { 'en': 'Blowfish Bell Hat', 'ja': 'フグベルハット' },
    'bobble_hat': { 'en': 'Bobble Hat', 'ja': 'ボンボンニット' },
    'camo_mesh': { 'en': 'Camo Mesh', 'ja': 'カモメッシュ' },
    'camping_hat': { 'en': 'Camping Hat', 'ja': 'キャンプハット' },
    'corocoro_cap': { 'en': 'CoroCoro Cap', 'ja': 'コロコロキャップ' },
    'classic_straw_boater': { 'en': 'Classic Straw Boater', 'ja': 'イカンカン クラシック' },
    'clycling_cap': { 'en': 'Clycling Cap', 'ja': 'テッカサイクルキャップ' },
    'cycle_king_cap': { 'en': 'Cycle King Cap', 'ja': 'チャリキング帽' },
    'designer_headphones': { 'en': 'Designer Headphones', 'ja': 'オーロラヘッドホン' },
    'fake_contacts': { 'en': 'Fake Contacts', 'ja': 'ダテコンタクト' },
    'fishfry_visor': { 'en': 'FishFry Visor', 'ja': 'ヤキフグ サンバイザー' },
    'five_panel_cap': { 'en': 'Five-Panel Cap', 'ja': '5パネルキャップ' },
    'full_moon_glasses': { 'en': 'Full Moon Glasses', 'ja': 'マルベッコー' },
    'gas_mask': { 'en': 'Gas Mask', 'ja': 'タコマスク' },
    'golf_visor': { 'en': 'Golf Visor', 'ja': 'キャディ サンバイザー' },
    'hero_headset_replica': { 'en': 'Hero Headset Replica', 'ja': 'ヒーローヘッズ レプリカ' },
    'jet_cap': { 'en': 'Jet Cap', 'ja': 'ジェットキャップ' },
    'jogging_headband': { 'en': 'Jogging Headband', 'ja': 'ランニングバンド' },
    'jungle_hat': { 'en': 'Jungle Hat', 'ja': 'サファリハット' },
    'legendary_cap': { 'en': 'Legendary Cap', 'ja': 'でんせつのぼうし' },
    'lightweight_cap': { 'en': 'Lightweight Cap', 'ja': 'キャンプキャップ' },
    'noise_cancelers': { 'en': 'Noise Cancelers', 'ja': 'イヤーマフ' },
    'octoglasses': { 'en': 'Octoglasses', 'ja': 'オクタグラス' },
    'octoling_goggles': { 'en': 'Octoling Goggles', 'ja': 'タコゾネススコープ' },
    'paintball_mask': { 'en': 'Paintball Mask', 'ja': 'フェイスゴーグル' },
    'paisley_bandana': { 'en': 'Paisley Bandana', 'ja': 'エイズリーバンダナ' },
    'pilot_goggles': { 'en': 'Pilot Goggles', 'ja': 'パイロットゴーグル' },
    'power_mask': { 'en': 'Power Mask', 'ja': 'パワードマスク' },
    'retro_specs': { 'en': 'Retro Specs', 'ja': 'クロブチレトロ' },
    'safari_hat': { 'en': 'Safari Hat', 'ja': 'ロブスターブーニー' },
    'samurai_helmet': { 'en': 'Samurai Helmet', 'ja': 'サムライヘルメット' },
    'short_beanie': { 'en': 'Short Beanie', 'ja': 'ショートビーニー' },
    'skate_helmet': { 'en': 'Skate Helmet', 'ja': 'スケボーメット' },
    'skull_bandana': { 'en': 'Skull Bandana', 'ja': 'イカスカルマスク' },
    'snorkel_mask': { 'en': 'Snorkel Mask', 'ja': 'ダイバーゴーグル' },
    'soccer_headband': { 'en': 'Soccer Headband', 'ja': 'サッカーバンド' },
    'special_forces_beret': { 'en': 'Special Forces Beret', 'ja': 'モンゴウベレー' },
    'splash_goggles': { 'en': 'Splash Goggles', 'ja': 'スプラッシュゴーグル' },
    'sporty_bobble_hat': { 'en': 'Sporty Bobble Hat', 'ja': 'ウインターボンボン' },
    'squash_headband': { 'en': 'Squash Headband', 'ja': 'スカッシュバンド' },
    'squid_girl_hat': { 'en': 'SQUID GIRL Hat', 'ja': 'イカ娘ずきん' },
    'squid_hairclip': { 'en': 'Squid Hairclip', 'ja': 'イカパッチン' },
    'squid_nordic': { 'en': 'Squid Nordic', 'ja': 'イカノルディック' },
    'squid_stitch_cap': { 'en': 'Squid-Stitch Cap', 'ja': 'チドリキャップ' },
    'squidvader_cap': { 'en': 'Squidvader Cap', 'ja': 'イカベーダーキャップ' },
    'stealth_goggles': { 'en': 'Stealth Goggles', 'ja': 'ナイトビジョン' },
    'straw_boater': { 'en': 'Straw Boater', 'ja': 'イカンカン' },
    'streetstyle_cap': { 'en': 'Streetstyle Cap', 'ja': 'ビバレッジキャップ' },
    'striped_beanie': { 'en': 'Striped Beanie', 'ja': 'ボーダービーニー' },
    'studio_headphones': { 'en': 'Studio Headphones', 'ja': 'スタジオヘッドホン' },
    'sun_visor': { 'en': 'Sun Visor', 'ja': 'サンサンサンバイザー' },
    'takoroka_mesh': { 'en': 'Takoroka Mesh', 'ja': 'ヤコメッシュ' },
    'tennis_headband': { 'en': 'Tennis Headband', 'ja': 'テニスバンド' },
    'tentacles_helmet': { 'en': 'Tentacles Helmet', 'ja': 'テンタクルズメット' },
    'tinted_shades': { 'en': 'Tinted Shades', 'ja': 'イロメガネ' },
    'traditional_headband': { 'en': 'Traditional Headband', 'ja': 'タイショウのはちまき' },
    'treasure_hunter': { 'en': 'Treasure Hunter', 'ja': 'トレジャーメット' },
    'two_stripe_mesh': { 'en': 'Two-Stripe Mesh', 'ja': '2ラインメッシュ' },
    'urchins_cap': { 'en': 'Urchins Cap', 'ja': 'ウーニーズBBキャップ' },
    'visor_skate_helmet': { 'en': 'Visor Skate Helmet', 'ja': 'バイザーメット' },
    'white_arrowbands': { 'en': 'White Arrowbands', 'ja': 'アローバンド ホワイト' },
    'white_headband': { 'en': 'White Headband', 'ja': 'ヘッドバンド ホワイト' },
    'zekko_mesh': { 'en': 'Zekko Mesh', 'ja': 'エゾッコメッシュ' },
}

gear_clothing = {
    'aloha_shirt': { 'en': 'Aloha Shirt', 'ja': 'おどるイカアロハ' },
    'anchor_sweat': { 'en': 'Anchor Sweat', 'ja': 'イカリスウェット' },
    'armor_jacket_replica': { 'en': 'Armor Jacket Replica', 'ja': 'アーマージャケット レプリカ' },
    'b_ball_jersey_away': { 'en': 'B-ball Jersey (Away)', 'ja': 'バスケジャージ アウェイ' },
    'b_ball_jersey_home': { 'en': 'B-ball Jersey (Home)', 'ja': 'バスケジャージ ホーム' },
    'baby_jelly_shirt': { 'en': 'Baby-Jelly Shirt', 'ja': 'ベイビークラゲシャツ' },
    'baseball_jersey': { 'en': 'Baseball Jersey', 'ja': 'ミスターベースボール' },
    'basic_tee': { 'en': 'Basic Tee', 'ja': 'わかばイカT' },
    'berry_ski_jacket': { 'en': 'Berry Ski Jacket', 'ja': 'マウンテンベリー' },
    'black_8_bit_fishfry': { 'en': 'Black 8-Bit FishFry', 'ja': 'ヤキフグ8bit ブラック' },
    'black_anchor_tee': { 'en': 'Black Anchor Tee', 'ja': 'ガチブラック' },
    'black_baseball_ls': { 'en': 'Black Baseball LS', 'ja': 'ハラグロラグラン' },
    'black_inky_rider': { 'en': 'Black Inky Rider', 'ja': 'イカライダーBLACK' },
    'black_layered_ls': { 'en': 'Black Layered LS', 'ja': 'レイヤード ブラック' },
    'black_ls': { 'en': 'Black LS', 'ja': 'バニーポップ ブラック' },
    'black_pipe_tee': { 'en': 'Black Pipe Tee', 'ja': 'ドカンT ブラック' },
    'black_polo': { 'en': 'Black Polo', 'ja': 'ピンポンポロ' },
    'black_squideye': { 'en': 'Black Squideye', 'ja': 'イカノメT ブラック' },
    'black_tee': { 'en': 'Black Tee', 'ja': 'イカブラック' },
    'blue_peaks_tee': { 'en': 'Blue Peaks Tee', 'ja': 'ヤマビコT ブルー' },
    'blue_sailor_suit': { 'en': 'Blue Sailor Suit', 'ja': 'イカセーラー ブルー' },
    'camo_layered_ls': { 'en': 'Camo Layered LS', 'ja': 'カモガサネ' },
    'camo_zip_hoodie': { 'en': 'Camo Zip Hoodie', 'ja': 'ジップアップ カモ' },
    'carnivore_tee': { 'en': 'Carnivore Tee', 'ja': 'ニクショクT' },
    'choco_layered_ls': { 'en': 'Choco Layered LS', 'ja': 'チョコガサネ' },
    'corocoro_parka': { 'en': 'CoroCoro Parka', 'ja': 'コロコロパーカー' },
    'cycle_king_jersey': { 'en': 'Cycle King Jersey', 'ja': 'チャリキングジャージ' },
    'cycling_shirt': { 'en': 'Cycling Shirt', 'ja': 'テッカサイクルシャツ' },
    'dark_urban_vest': { 'en': 'Dark Urban Vest', 'ja': 'アーバンベスト ナイト' },
    'fc_albacore': { 'en': 'FC Albacore', 'ja': 'アオサドーレ' },
    'firefin_navy_sweat': { 'en': 'Firefin Navy Sweat', 'ja': 'ホッコリー ネイビー' },
    'forest_vest': { 'en': 'Forest Vest', 'ja': 'フォレストダウン' },
    'forge_inkling_parka': { 'en': 'Forge Inkling Parka', 'ja': 'F-190' },
    'forge_octarian_jacket': { 'en': 'Forge Octarian Jacket', 'ja': 'F-010' },
    'fugu_tee': { 'en': 'Fugu Tee', 'ja': 'マルフグT' },
    'grape_tee': { 'en': 'Grape Tee', 'ja': 'グレープT' },
    'gray_college_sweat': { 'en': 'Gray College Sweat', 'ja': 'カレッジスウェットグレー' },
    'gray_mixed_shirt': { 'en': 'Gray Mixed Shirt', 'ja': 'ミックスシャツ グレー' },
    'gray_vector_tee': { 'en': 'Gray Vector Tee', 'ja': 'ベクトルパターン グレー' },
    'green_cardigan': { 'en': 'Green Cardigan', 'ja': 'レタード グリーン' },
    'green_check_shirt': { 'en': 'Green-Check Shirt', 'ja': 'ギンガムチェック ミドリ' },
    'green_striped_ls': { 'en': 'Green Striped LS', 'ja': 'ボーダーモスグリーン' },
    'green_tee': { 'en': 'Green Tee', 'ja': 'グリーンT' },
    'green_zip_hoodie': { 'en': 'Green Zip Hoodie', 'ja': 'ジップアップ グリーン' },
    'herbivore_tee': { 'en': 'Herbivore Tee', 'ja': 'ソウショクT' },
    'hero_jacket_replica': { 'en': 'Hero Jacket Replica', 'ja': 'ヒーロージャケット レプリカ' },
    'ivory_peaks_tee': { 'en': 'Ivory Peaks Tee', 'ja': 'ヤマビコT アイボリー' },
    'krak_on_528': { 'en': 'Krak-On 528', 'ja': 'クラーゲス528' },
    'layered_anchor_ls': { 'en': 'Layered Anchor LS', 'ja': 'ガチガサネ' },
    'layered_vector_ls': { 'en': 'Layered Vector LS', 'ja': 'ベクトルラインガサネ' },
    'linen_shirt': { 'en': 'Linen Shirt', 'ja': 'シャンブレーシャツ' },
    'loga_aloha_shirt': { 'en': 'Loga Aloha Shirt', 'ja': 'ロゴマシマシアロハ' },
    'mint_tee': { 'en': 'Mint Tee', 'ja': 'ミントT' },
    'mountain_vest': { 'en': 'Mountain Vest', 'ja': 'マウンテンダウン' },
    'navy_college_sweat': { 'en': 'Navy College Sweat', 'ja': 'カレッジスウェット ネイビー' },
    'navy_striped_ls': { 'en': 'Navy Striped LS', 'ja': 'ボーダーネイビー' },
    'octo_tee': { 'en': 'Octo Tee', 'ja': 'タコT' },
    'octoling_armor': { 'en': 'Octoling Armor', 'ja': 'タコゾネスプロテクター' },
    'olive_ski_jacket': { 'en': 'Olive Ski Jacket', 'ja': 'マウンテンオリーブ' },
    'orange_cardigan': { 'en': 'Orange Cardigan', 'ja': 'レタード オレンジ' },
    'part_time_pirate': { 'en': 'Part-Time Pirate', 'ja': 'かくれパイレーツ' },
    'pearl_tee': { 'en': 'Pearl Tee', 'ja': 'パールドットT' },
    'pirate_stripe_tee': { 'en': 'Pirate-Stripe Tee', 'ja': 'パイレーツボーダー' },
    'power_armor': { 'en': 'Power Armor', 'ja': 'パワードスーツ' },
    'purple_camo_ls': { 'en': 'Purple Camo LS', 'ja': 'カモフラパープル' },
    'rainy_day_tee': { 'en': 'Rainy-Day Tee', 'ja': 'レイニーブルーT' },
    'red_check_shirt': { 'en': 'Red-Check Shirt', 'ja': 'ギンガムチェック アカ' },
    'red_vector_tee': { 'en': 'Red Vector Tee', 'ja': 'ベクトルパターン レッド' },
    'reel_sweat': { 'en': 'Reel Sweat', 'ja': 'リールロールスウェット' },
    'reggae_tee': { 'en': 'Reggae Tee', 'ja': 'イカジャマイカ' },
    'retro_gamer_jersey': { 'en': 'Retro Gamer Jersey', 'ja': 'FCジャージー' },
    'retro_sweat': { 'en': 'Retro Sweat', 'ja': 'レトロジャッジ' },
    'rockenberg_black': { 'en': 'Rockenberg Black', 'ja': 'ロッケンベルグT ブラック' },
    'rockenberg_white': { 'en': 'Rockenberg White', 'ja': 'ロッケンベルグT ホワイト' },
    'round_collar_shirt': { 'en': 'Round-Collar Shirt', 'ja': 'マルエリシャツ' },
    'sage_polo': { 'en': 'Sage Polo', 'ja': 'よもぎポロ' },
    'sailor_stripe_tee': { 'en': 'Sailor-Stripe Tee', 'ja': 'マリンボーダー' },
    'samurai_jacket': { 'en': 'Samurai Jacket', 'ja': 'サムライジャケット' },
    'school_uniform': { 'en': 'School Uniform', 'ja': 'スクールブレザー' },
    'shirt_and_tie': { 'en': 'Shirt & Tie', 'ja': 'タイシャツ' },
    'shrimp_pink_polo': { 'en': 'Shrimp-Pink Polo', 'ja': 'さくらエビポロ' },
    'sky_blue_squideye': { 'en': 'Sky-Blue Squideye', 'ja': 'イカノメT ライトブルー' },
    'slipstream_united': { 'en': 'Slipstream United', 'ja': 'FCカラスミ' },
    'splatfest_tee': { 'en': 'Splatfest Tee', 'ja': 'フェスT' },
    'squid_girl_tunic': { 'en': 'SQUID GIRL Tunic', 'ja': 'イカ娘ノースリーブ' },
    'squid_pattern_waistcoat': { 'en': 'Squid-Pattern Waistcoat', 'ja': 'イカゴッチンベスト' },
    'squid_satin_jacket': { 'en': 'Squid Satin Jacket', 'ja': 'イカスカジャン' },
    'squid_stitch_tee': { 'en': 'Squid-Stitch Tee', 'ja': 'チドリメロンT' },
    'squidmark_ls': { 'en': 'Squidmark LS', 'ja': 'イカバッテンロング' },
    'squidmark_sweat': { 'en': 'Squidmark Sweat', 'ja': 'イカバッテン マスタード' },
    'squidstar_waistcoat': { 'en': 'Squidstar Waistcoat', 'ja': 'イカノボリベスト' },
    'striped_peaks_ls': { 'en': 'Striped Peaks LS', 'ja': 'ヤマビコボーダー' },
    'striped_rugby': { 'en': 'Striped Rugby', 'ja': 'オレンジボーダーラガー' },
    'striped_shirt': { 'en': 'Striped Shirt', 'ja': 'ブロックストライプシャツ' },
    'sunny_day_tee': { 'en': 'Sunny-Day Tee', 'ja': 'サニーオレンジT' },
    'traditional_apron': { 'en': 'Traditional Apron', 'ja': 'タイショウのまえかけ' },
    'tricolor_rugby': { 'en': 'Tricolor Rugby', 'ja': 'トリコロールラガー' },
    'urchins_jersey': { 'en': 'Urchins Jersey', 'ja': 'ウーニーズBBシャツ' },
    'varsity_baseball_ls': { 'en': 'Varsity Baseball LS', 'ja': 'カレッジラグラン' },
    'varsity_jacket': { 'en': 'Varsity Jacket', 'ja': 'スタジャンロゴマシ' },
    'vintage_check_shirt': { 'en': 'Vintage Check Shirt', 'ja': 'ヴィンテージチェック' },
    'white_8_bit_fishfry': { 'en': 'White 8-Bit FishFry', 'ja': 'ヤキフグ8bit ホワイト' },
    'white_anchor_tee': { 'en': 'White Anchor Tee', 'ja': 'ガチホワイト' },
    'white_baseball_ls': { 'en': 'White Baseball LS', 'ja': 'ハラシロラグラン' },
    'white_inky_rider': { 'en': 'White Inky Rider', 'ja': 'イカライダーWHITE' },
    'white_layered_ls': { 'en': 'White Layered LS', 'ja': 'レイヤード ホワイト' },
    'white_line_tee': { 'en': 'White Line Tee', 'ja': 'ラインT ホワイト' },
    'white_sailor_suit': { 'en': 'White Sailor Suit', 'ja': 'イカセーラー ホワイト' },
    'white_shirt': { 'en': 'White Shirt', 'ja': 'シロシャツ' },
    'white_striped_ls': { 'en': 'White Striped LS', 'ja': 'ボーダーホワイト' },
    'white_tee': { 'en': 'White Tee', 'ja': 'イカホワイト' },
    'yellow_layered_ls': { 'en': 'Yellow Layered LS', 'ja': 'マスタードガサネ' },
    'yellow_urban_vest': { 'en': 'Yellow Urban Vest', 'ja': 'アーバンベスト イエロー' },
    'zapfish_satin_jacket': { 'en': 'Zapfish Satin Jacket', 'ja': 'ウラスカジャン' },
    'zekko_basseball_ls': { 'en': 'Zekko Basseball LS', 'ja': 'エゾッコラグラン' },
    'zekko_hoodie': { 'en': 'Zekko Hoodie', 'ja': 'エゾッコパーカー アズキ' },
    'zink_layered_ls': { 'en': 'Zink Layered LS', 'ja': 'アイロニックレイヤード' },
    'zink_ls': { 'en': 'Zink LS', 'ja': 'アイロニックロング' },
}

gear_shoes = {
    'acerola_rain_boots': { 'en': 'Acerola Rain Boots', 'ja': 'レイニーアセロラ' },
    'armor_boot_replicas': { 'en': 'Armor Boot Replicas', 'ja': 'アーマーブーツ レプリカ' },
    'banana_basics': { 'en': 'Banana Basics', 'ja': 'キャンバス バナナ' },
    'black_seahorses': { 'en': 'Black Seahorses', 'ja': 'シーホース ブラックレザー' },
    'black_trainers': { 'en': 'Black Trainers', 'ja': 'ブラックビーンズ' },
    'blue_lo_tops': { 'en': 'Blue Lo-Tops', 'ja': 'グリッチョブルー' },
    'blue_moto_boots': { 'en': 'Blue Moto Boots', 'ja': 'モトクロスソリッド ブルー' },
    'blue_sea_slugs': { 'en': 'Blue Sea Slugs', 'ja': 'ウミウシブルー' },
    'blue_slip_ons': { 'en': 'Blue Slip-Ons', 'ja': 'スリッポン ブルー' },
    'blueberry_casuals': { 'en': 'Blueberry Casuals', 'ja': 'ブルーベリーコンフォート' },
    'bubble_rain_boots': { 'en': 'Bubble Rain Boots', 'ja': 'レイニーシャボン' },
    'cherry_kicks': { 'en': 'Cherry Kicks', 'ja': 'ラバーソール チェリー' },
    'choco_clogs': { 'en': 'Choco Clogs', 'ja': 'チョコクロッグ' },
    'clownfish_basics': { 'en': 'Clownfish Basics', 'ja': 'キャンバス クマノミ' },
    'crazy_arrows': { 'en': 'Crazy Arrows', 'ja': 'クレイジーアローズ' },
    'cream_basics': { 'en': 'Cream Basics', 'ja': 'キャンバス ホワイト' },
    'cream_hi_tops': { 'en': 'Cream Hi-Tops', 'ja': 'キャンバスHi マッシュルーム' },
    'custom_trail_boots': { 'en': 'Custom Trail Boots', 'ja': 'トレッキングカスタム' },
    'cyan_trainers': { 'en': 'Cyan Trainers', 'ja': 'シアンビーンズ' },
    'gold_hi_horses': { 'en': 'Gold Hi-Horses', 'ja': 'シーホースHi ゴールド' },
    'green_rain_boots': { 'en': 'Green Rain Boots', 'ja': 'レイニーモスグリーン' },
    'hero_runner_replicas': { 'en': 'Hero Runner Replicas', 'ja': 'ヒーローキックス レプリカ' },
    'hunter_hi_tops': { 'en': 'Hunter Hi-Tops', 'ja': 'キャンバスHi モロヘイヤ' },
    'icy_down_boots': { 'en': 'Icy Down Boots', 'ja': 'アイスダウンブーツ' },
    'le_lo_tops': { 'en': 'LE Lo-Tops', 'ja': 'グリッチョ グリーン 限定版' },
    'le_soccer_cleats': { 'en': 'LE Soccer Cleats', 'ja': 'レアスパイカ' },
    'mawcasins': { 'en': 'Mawcasins', 'ja': 'ジョーズモカシン' },
    'moto_boots': { 'en': 'Moto Boots', 'ja': 'モトクロスブーツ' },
    'neon_sea_slugs': { 'en': 'Neon Sea Slugs', 'ja': 'ウミウシイエロー' },
    'octoling_boots': { 'en': 'Octoling Boots', 'ja': 'タコゾネスブーツ' },
    'orange_arrows': { 'en': 'Orange Arrows', 'ja': 'オレンジアローズ' },
    'orange_lo_tops': { 'en': 'Orange Lo-Tops', 'ja': 'グリッチョ オレンジ' },
    'oyster_clogs': { 'en': 'Oyster Clogs', 'ja': 'オイスタークロッグ' },
    'pink_trainers': { 'en': 'Pink Trainers', 'ja': 'ピンクビーンズ' },
    'plum_casuals': { 'en': 'Plum Casuals', 'ja': 'アケビコンフォート' },
    'power_boots': { 'en': 'Power Boots', 'ja': 'パワードレッグス' },
    'pro_trail_boots': { 'en': 'Pro Trail Boots', 'ja': 'トレッキングプロ' },
    'punk_cherries': { 'en': 'Punk Cherries', 'ja': 'ロッキンチェリー' },
    'punk_whites': { 'en': 'Punk Whites', 'ja': 'ロッキンホワイト' },
    'punk_yellows': { 'en': 'Punk Yellows', 'ja': 'ロッキンイエロー' },
    'purple_hi_horses': { 'en': 'Purple Hi-Horses', 'ja': 'シーホースHi パープル' },
    'purple_sea_slugs': { 'en': 'Purple Sea Slugs', 'ja': 'ウミウシパープル' },
    'red_hi_horses': { 'en': 'Red Hi-Horses', 'ja': 'シーホースHi レッド' },
    'red_hi_tops': { 'en': 'Red Hi-Tops', 'ja': 'キャンバスHi トマト' },
    'red_sea_slugs': { 'en': 'Red Sea Slugs', 'ja': 'ウミウシレッド' },
    'red_slip_ons': { 'en': 'Red Slip-Ons', 'ja': 'スリッポン レッド' },
    'red_work_boots': { 'en': 'Red Work Boots', 'ja': 'ヌバックブーツ レッド' },
    'roasted_brogues': { 'en': 'Roasted Brogues', 'ja': 'イカヤキチップ' },
    'samurai_shoes': { 'en': 'Samurai Shoes', 'ja': 'サムライシューズ' },
    'school_shoes': { 'en': 'School Shoes', 'ja': 'スクールローファー' },
    'shark_moccasins': { 'en': 'Shark Moccasins', 'ja': 'シャークモカシン' },
    'snowy_down_boots': { 'en': 'Snowy Down Boots', 'ja': 'ミルキーダウンブーツ' },
    'soccer_cleats': { 'en': 'Soccer Cleats', 'ja': 'ユデスパイカ' },
    'squid_girl_shoes': { 'en': 'SQUID GIRL Shoes', 'ja': 'イカ娘シューズ' },
    'squid_stitch_slip_ons': { 'en': 'Squid-Stitch Slip-Ons', 'ja': 'スリッポン チドリ' },
    'squink_wingtops': { 'en': 'Squink Wingtops', 'ja': 'イカスミチップ' },
    'strapping_reds': { 'en': 'Strapping Reds', 'ja': 'ベリベリレッド' },
    'strapping_whites': { 'en': 'Strapping Whites', 'ja': 'ベリベリホワイト' },
    'tan_work_boots': { 'en': 'Tan Work Boots', 'ja': 'ヌバックブーツ イエロー' },
    'traditional_sandals': { 'en': 'Traditional Sandals', 'ja': 'タイショウのげた' },
    'trail_boots': { 'en': 'Trail Boots', 'ja': 'トレッキングライト' },
    'turquoise_kicks': { 'en': 'Turquoise Kicks', 'ja': 'ラバーソール ターコイズ' },
    'white_arrows': { 'en': 'White Arrows', 'ja': 'ホワイトアローズ' },
    'white_kicks': { 'en': 'White Kicks', 'ja': 'ラバーソール ホワイト' },
    'white_seahorses': { 'en': 'White Seahorses', 'ja': 'シーホース ホワイト' },
    'yellow_seahorses': { 'en': 'Yellow Seahorses', 'ja': 'シーホース イエロー' },
    'zombie_hi_horses': { 'en': 'Zombie Hi-Horses', 'ja': 'シーホースHi ゾンビ' },
}

lobby_types = {
    'festa':    {'ja': 'フェス', 'en': 'Splatfest'},
    'private':  {'ja': 'プライベートマッチ', 'en': 'Private Battle'},
    'public':   {'ja': '通常マッチ', 'en': 'Standard Battle'},
    'tag':      {'ja': 'タッグマッチ', 'en': 'Squad Battle'},
}

#

upcoming_weapons = [
]

#

for ability in gear_abilities.keys():
    gear_abilities[ability]['id'] = ability

for brand in gear_brands.keys():
    gear_brands[brand]['id'] = brand
